# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96b8af3c698f3ba20a55215bb3d9faa7e6c5e7ff702848845fbe10f5bf471dfb4b2bdf0f02d13b4a3c78102a2ccb06cd295afd0369143d9d4dfba26ef6f10d3c

test:
  secret_key_base: 6642a866e4f5d4ff295e72cb3c8a614f3b0a1899b1e0e60a26193b4bf30d1a4e4b70db92d4f97cb5dc93f013931ad318cdf861f573519ed9a7f5a9463c96fd71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
